CREATE DATABASE wechat;
CREATE USER xxw WITH PASSWORD 'Zeus000!';
GRANT ALL PRIVILEGES ON DATABASE wechat to xxw;

CREATE DATABASE csdw;
CREATE USER tpch WITH PASSWORD 'Zeus000!';
GRANT ALL PRIVILEGES ON DATABASE csdw to tpch;
\du
\l
